load("//tools:defs.bzl", "go_library")

package(licenses = ["notice"])

go_library(
    name = "crypto",
    # TODO(b/170401822): Add google implementations using gr0 API.
    srcs = [
        "crypto.go",
    ],
    visibility = ["//:sandbox"],
)
